- name: Steps 7, 8 & 9 - SSH to EC2 and Update Kubernetes
      uses: appleboy/ssh-action@v1.0.3
      env:
       
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        AWS_REGION: ${{ env.AWS_REGION }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }} # Recommended: latest ki jagah commit SHA use karein
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        
        envs: ECR_REGISTRY,AWS_REGION,ECR_REPOSITORY,IMAGE_TAG
        script: |
          set -e
          echo "Successfully SSHed into EC2 instance!"
          
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          
         docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          if [ -f deployment.yaml ]; then
            kubectl apply -f deployment.yaml
          fi
            kubectl set image deployment/node-app-deployment node-app-container=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment/node-app-deployment